apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-tutorial
  namespace: gitops-tutorial
spec:
  project: gitops-tutorial
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: environments/dev/apps/gitops-tutorial
    repoURL: 'https://github.com/ugursogukpinar/gitops-tutorial'
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
