apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gitops-tutorial
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: GitOps Tutorial
  sourceRepos:
  - 'https://github.com/ugursogukpinar/gitops-tutorial'
  # Only permit applications to deploy to the gitops-tutorial namespace in the same cluster
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
  - namespace: gitops-tutorial
    server: https://kubernetes.default.svc