apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-tutorial
  namespace: argocd
spec:
  destination:
    namespace: gitops-tutorial
    server: 'https://kubernetes.default.svc'
  source:
    path: environments/dev/apps
    repoURL: 'https://github.com/ugursogukpinar/gitops-tutorial'
    targetRevision: HEAD
    directory:
      recurse: true
  project: gitops-tutorial
  syncPolicy:
    automated:
      prune: true
      selfHeal: true