apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-test-service-2
  namespace: argocd
spec:
  project: gitops-tutorial
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-tutorial
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
  source:
    repoURL: https://github.com/ugursogukpinar/gitops-tutorial.git
    path: helm-templates
    targetRevision: main

    helm:
      valueFiles:
        - ../environments/dev/apps/gitops-tutorial/nginx-test-service-2/values.yml