apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-test-service-1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: gitops-tutorial
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-tutorial
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
  source:
    repoURL: https://github.com/ugursogukpinar/gitops-tutorial
    chart: helm-templates
    targetRevision: main

    helm:
      values: |
        image:
          repository: nginx
          pullPolicy: IfNotPresent
          tag: "latest"

        nameOverride: "nginx-test-service-1"
        fullnameOverride: "nginx-test-service-1"

        resources:
          limits:
            cpu: 1000m
            memory: 128Mi
          requests:
            cpu: 500m
            memory: 128Mi