image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: "nginx-test-service-1"
fullnameOverride: "nginx-test-service-1"

resources:
  limits:
    cpu: 1000m
    memory: 128Mi
  requests:
    cpu: 500m
    memory: 128Mi